

service: ${self:custom.config.service-name}
frameworkVersion: ${self:custom.config.framework-version}

provider:
  name: aws
  runtime: nodejs12.x
  profile: pdfapiservice
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

layers: ${file(./serverless-yml/layers.yml)}
custom: ${file(./serverless-yml/custom.yml)}

functions: ${file(./serverless-dynamic.js):functions}
